using AutoMapper;
using SoftTime.Application.DTOs;
using SoftTime.Domain.Entities.SoftTime;

namespace SoftTime.Application.Mapping;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<T_ROLE, RoleDto>().ForMember(d => d.Id, o => o.MapFrom(s => s.IDROLE)).ForMember(d => d.Nom, o => o.MapFrom(s => s.NOMROLE));
        CreateMap<T_DROIT, DroitDto>().ForMember(d => d.Id, o => o.MapFrom(s => s.IDDROIT)).ForMember(d => d.Nom, o => o.MapFrom(s => s.DROIT));
        CreateMap<T_BDD_SAGE, SageDbDto>()
            .ForMember(d => d.Id, o => o.MapFrom(s => s.ID))
            .ForMember(d => d.SqlAuth, o => o.MapFrom(s => s.TYPE_AUTH))
            .ForMember(d => d.NomBd, o => o.MapFrom(s => s.NOM_BD))
            .ForMember(d => d.Password, o => o.MapFrom(s => s.TMDP))
            .ForMember(d => d.Login, o => o.MapFrom(s => s.TLOGIN))
            .ForMember(d => d.TypeBase, o => o.MapFrom(s => s.TYPE_BASE))
            .ForMember(d => d.MapTable, o => o.MapFrom(s => s.MAP_TABLE))
            .ForMember(d => d.MapColMatricule, o => o.MapFrom(s => s.MAP_COL_MATRICULE))
            .ForMember(d => d.MapColNom, o => o.MapFrom(s => s.MAP_COL_NOM))
            .ForMember(d => d.MapColPrenom, o => o.MapFrom(s => s.MAP_COL_PRENOM))
            .ForMember(d => d.MapColBadge, o => o.MapFrom(s => s.MAP_COL_BADGE))
            .ForMember(d => d.MapColDepartement, o => o.MapFrom(s => s.MAP_COL_DEPARTEMENT))
            .ForMember(d => d.MapColService, o => o.MapFrom(s => s.MAP_COL_SERVICE))
            .ForMember(d => d.MapColCodeDepartement, o => o.MapFrom(s => s.MAP_COL_CODE_DEPARTEMENT))
            .ForMember(d => d.MapTableCodeConstante, o => o.MapFrom(s => s.MAP_TABLE_CODE_CONSTANTE))
            .ForMember(d => d.MapColCodeConstante, o => o.MapFrom(s => s.MAP_COL_CODE_CONSTANTE));
        CreateMap<SageDbDto, T_BDD_SAGE>()
            .ForMember(d => d.TYPE_AUTH, o => o.MapFrom(s => s.SqlAuth))
            .ForMember(d => d.NOM_BD, o => o.MapFrom(s => s.NomBd))
            .ForMember(d => d.TMDP, o => o.MapFrom(s => s.Password))
            .ForMember(d => d.TLOGIN, o => o.MapFrom(s => s.Login))
            .ForMember(d => d.SERVEUR, o => o.MapFrom(s => s.Serveur))
            .ForMember(d => d.TYPE_BASE, o => o.MapFrom(s => s.TypeBase))
            .ForMember(d => d.MAP_TABLE, o => o.MapFrom(s => s.MapTable))
            .ForMember(d => d.MAP_COL_MATRICULE, o => o.MapFrom(s => s.MapColMatricule))
            .ForMember(d => d.MAP_COL_NOM, o => o.MapFrom(s => s.MapColNom))
            .ForMember(d => d.MAP_COL_PRENOM, o => o.MapFrom(s => s.MapColPrenom))
            .ForMember(d => d.MAP_COL_BADGE, o => o.MapFrom(s => s.MapColBadge))
            .ForMember(d => d.MAP_COL_DEPARTEMENT, o => o.MapFrom(s => s.MapColDepartement))
            .ForMember(d => d.MAP_COL_SERVICE, o => o.MapFrom(s => s.MapColService))
            .ForMember(d => d.MAP_COL_CODE_DEPARTEMENT, o => o.MapFrom(s => s.MapColCodeDepartement))
            .ForMember(d => d.MAP_TABLE_CODE_CONSTANTE, o => o.MapFrom(s => s.MapTableCodeConstante))
            .ForMember(d => d.MAP_COL_CODE_CONSTANTE, o => o.MapFrom(s => s.MapColCodeConstante));
        CreateMap<T_BDD_POINTEUSE, PointeuseDbDto>()
            .ForMember(d => d.Id, o => o.MapFrom(s => s.ID))
            .ForMember(d => d.SqlAuth, o => o.MapFrom(s => s.TYPE_AUTH))
            .ForMember(d => d.NomBd, o => o.MapFrom(s => s.NOM_BD))
            .ForMember(d => d.Password, o => o.MapFrom(s => s.TMDP))
            .ForMember(d => d.Login, o => o.MapFrom(s => s.TLOGIN))
            .ForMember(d => d.TypePointage, o => o.MapFrom(s => s.TYPE_POINTAGE))
            .ForMember(d => d.Active, o => o.MapFrom(s => s.ACTIVE))
            .ForMember(d => d.TypeBase, o => o.MapFrom(s => s.TYPE_BASE))
            .ForMember(d => d.MapUserTable, o => o.MapFrom(s => s.MAP_USER_TABLE))
            .ForMember(d => d.MapUserColId, o => o.MapFrom(s => s.MAP_USER_COL_ID))
            .ForMember(d => d.MapUserColBadge, o => o.MapFrom(s => s.MAP_USER_COL_BADGE))
            .ForMember(d => d.MapUserColSsn, o => o.MapFrom(s => s.MAP_USER_COL_SSN))
            .ForMember(d => d.MapUserColNom, o => o.MapFrom(s => s.MAP_USER_COL_NOM))
            .ForMember(d => d.MapPunchTable, o => o.MapFrom(s => s.MAP_PUNCH_TABLE))
            .ForMember(d => d.MapPunchColUserId, o => o.MapFrom(s => s.MAP_PUNCH_COL_USER_ID))
            .ForMember(d => d.MapPunchColDateTime, o => o.MapFrom(s => s.MAP_PUNCH_COL_DATETIME))
            .ForMember(d => d.MapPunchColType, o => o.MapFrom(s => s.MAP_PUNCH_COL_TYPE));
        CreateMap<PointeuseDbDto, T_BDD_POINTEUSE>()
            .ForMember(d => d.TYPE_AUTH, o => o.MapFrom(s => s.SqlAuth))
            .ForMember(d => d.NOM_BD, o => o.MapFrom(s => s.NomBd))
            .ForMember(d => d.TMDP, o => o.MapFrom(s => s.Password))
            .ForMember(d => d.TLOGIN, o => o.MapFrom(s => s.Login))
            .ForMember(d => d.TYPE_POINTAGE, o => o.MapFrom(s => s.TypePointage))
            .ForMember(d => d.ACTIVE, o => o.MapFrom(s => s.Active))
            .ForMember(d => d.SERVEUR, o => o.MapFrom(s => s.Serveur))
            .ForMember(d => d.TYPE_BASE, o => o.MapFrom(s => s.TypeBase))
            .ForMember(d => d.MAP_USER_TABLE, o => o.MapFrom(s => s.MapUserTable))
            .ForMember(d => d.MAP_USER_COL_ID, o => o.MapFrom(s => s.MapUserColId))
            .ForMember(d => d.MAP_USER_COL_BADGE, o => o.MapFrom(s => s.MapUserColBadge))
            .ForMember(d => d.MAP_USER_COL_SSN, o => o.MapFrom(s => s.MapUserColSsn))
            .ForMember(d => d.MAP_USER_COL_NOM, o => o.MapFrom(s => s.MapUserColNom))
            .ForMember(d => d.MAP_PUNCH_TABLE, o => o.MapFrom(s => s.MapPunchTable))
            .ForMember(d => d.MAP_PUNCH_COL_USER_ID, o => o.MapFrom(s => s.MapPunchColUserId))
            .ForMember(d => d.MAP_PUNCH_COL_DATETIME, o => o.MapFrom(s => s.MapPunchColDateTime))
            .ForMember(d => d.MAP_PUNCH_COL_TYPE, o => o.MapFrom(s => s.MapPunchColType));
        CreateMap<T_CARDPAIE, CardPaieDto>()
            .ForMember(d => d.SageMatricule, o => o.MapFrom(s => s.SAGE_MATRICULE))
            .ForMember(d => d.SageNom, o => o.MapFrom(s => s.SAGE_NOM))
            .ForMember(d => d.SagePrenom, o => o.MapFrom(s => s.SAGE_PRENOM))
            .ForMember(d => d.PointeuseNumero, o => o.MapFrom(s => s.POINTEUSE_NUMERO))
            .ForMember(d => d.PointeuseNom, o => o.MapFrom(s => s.POINTEUSE_NOM))
            .ForMember(d => d.SageServeur, o => o.MapFrom(s => s.SAGE_SERVEUR))
            .ForMember(d => d.PointeuseServeur, o => o.MapFrom(s => s.POINTEUSE_SERVEUR))
            .ForMember(d => d.SageBdd, o => o.MapFrom(s => s.SAGE_BDD))
            .ForMember(d => d.PointeuseBdd, o => o.MapFrom(s => s.POINTEUSE_BDD))
            .ForMember(d => d.Origine, o => o.MapFrom(s => s.ORIGINE))
            .ForMember(d => d.Actif, o => o.MapFrom(s => s.ACTIF))
            .ForMember(d => d.Departement, o => o.MapFrom(s => s.DEPARTEMENT));
        CreateMap<CardPaieDto, T_CARDPAIE>()
            .ForMember(d => d.SAGE_MATRICULE, o => o.MapFrom(s => s.SageMatricule))
            .ForMember(d => d.BRANCHE, o => o.MapFrom(s => s.Branche))
            .ForMember(d => d.SAGE_NOM, o => o.MapFrom(s => s.SageNom))
            .ForMember(d => d.SAGE_PRENOM, o => o.MapFrom(s => s.SagePrenom))
            .ForMember(d => d.POINTEUSE_NUMERO, o => o.MapFrom(s => s.PointeuseNumero))
            .ForMember(d => d.POINTEUSE_NOM, o => o.MapFrom(s => s.PointeuseNom))
            .ForMember(d => d.SAGE_SERVEUR, o => o.MapFrom(s => s.SageServeur))
            .ForMember(d => d.POINTEUSE_SERVEUR, o => o.MapFrom(s => s.PointeuseServeur))
            .ForMember(d => d.SAGE_BDD, o => o.MapFrom(s => s.SageBdd))
            .ForMember(d => d.POINTEUSE_BDD, o => o.MapFrom(s => s.PointeuseBdd));
        CreateMap<T_CATEGORIE, CategoryDto>()
            .ForMember(d => d.Id, o => o.MapFrom(s => s.IDCATEGORIE))
            .ForMember(d => d.SupervisorCardId, o => o.MapFrom(s => s.ID_CARDPAIE))
            .ForMember(d => d.HeuresSemaine, o => o.MapFrom(s => s.HEURESEMAINE));
        CreateMap<T_MAJORATION, MajorationDto>();
        CreateMap<T_CODE_CONSTANTE, CodeConstanteDto>()
            .ForMember(d => d.Id, o => o.MapFrom(s => s.ID))
            .ForMember(d => d.Categorie, o => o.MapFrom(s => s.CATEGORIE))
            .ForMember(d => d.Intitule, o => o.MapFrom(s => s.INTITULE))
            .ForMember(d => d.CodeConstante, o => o.MapFrom(s => s.CODE_CONSTANTE))
            .ForMember(d => d.TableCible, o => o.MapFrom(s => s.TABLE_CIBLE));
        CreateMap<T_FERIE, HolidayDto>();
        CreateMap<T_PLANNING, ShiftDto>()
            .ForMember(d => d.Id, o => o.MapFrom(s => s.IDPLANNING))
            .ForMember(d => d.NoShift, o => o.MapFrom(s => s.NoSHIFT))
            .ForMember(d => d.Ha, o => o.MapFrom(s => s.HA))
            .ForMember(d => d.Hd, o => o.MapFrom(s => s.HD));
    }
}
